---
openapi: 3.1.0
info:
  title: Monstres API
  summary: This is the API of the Monstres service
  description: 
tags:
- name: admins
  description: game admins
- name: reporters
  description: can extract stats from the game
- name: users
  description: default
paths:
  /monstre:
    post:
      tags:
      - users
      operationId: add_monstre
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monstre'
    get:
      tags:
      - users
      operationId: get_monstre
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monstre'
    /monstre/{masterid}:
    get:
      tags:
      - users
      summary: get the monsters from a master
      operationId: get_monsters_by_masterid
      parameters:
      - name: masterid
        in: path
        description: Master ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Monsters of the master
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllMonsters'
        "400":
          description: bad input parameter
components:
  schemas:
    AllMonsters:
      type: array
      items:
        $ref: '#/components/schemas/Monstre'
    Monstre:
      type: object
      required:
        - id
        - name
        - puissance
        - nb_combats
        - nb_victoires
        - master_id
        - prix 
        - num_equipe
        - monsterdex_ref
      properties:
        id:
          type: int
          example: 1
        name:
          type: string
          example: "Pikachu"
        puissance:
          type: int
          example: 100
        nb_combats:
          type: int 
          example: 5
        nb_victoires:
          type: int 
          example: 4
        master_id:
          type: int 
          example: 2
        prix:
          type: int 
          example: 200
        num_equipe:
          type: int 
          example: 1
        monsterdex_ref:
          type: int
          example: 3


