/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **matches**
   * - Table in database
   */
  export namespace matches {
    export type Table = 'matches';
    export interface Selectable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matches.status**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      status: string;
      /**
      * **matches.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1: number;
      /**
      * **matches.p2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p2: number;
      /**
      * **matches.current_round**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      current_round: number;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      winner: number | null;
      /**
      * **matches.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at: Date | null;
      /**
      * **matches.ended_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ended_at: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matches.status**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      status: string;
      /**
      * **matches.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1: number;
      /**
      * **matches.p2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p2: number;
      /**
      * **matches.current_round**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      current_round: number;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      winner: number | null;
      /**
      * **matches.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at: db.TimestampString | null;
      /**
      * **matches.ended_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ended_at: db.TimestampString | null;
    }
    export interface Whereable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.status**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      status?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.p2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p2?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.current_round**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      current_round?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      winner?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.ended_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ended_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **matches.status**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      status: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **matches.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **matches.p2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p2: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **matches.current_round**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      current_round: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      winner?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.ended_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ended_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.status**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      status?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **matches.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **matches.p2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p2?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **matches.current_round**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      current_round?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, default: `0`
      */
      winner?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.ended_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      ended_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'matches_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = matches.Table;
    export type Selectable = matches.Selectable;
    export type JSONSelectable = matches.JSONSelectable;
    export type Whereable = matches.Whereable;
    export type Insertable = matches.Insertable;
    export type Updatable = matches.Updatable;
    export type UniqueIndex = matches.UniqueIndex;
    export type Column = matches.Column;
  
    export type AllBaseTables = [matches.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [matches.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "matches": matches.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "matches": matches.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "matches": matches.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "matches": matches.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "matches": matches.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "matches": matches.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "matches": matches.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "matches": matches.SQL;
  }[T];

}
