---
openapi: 3.1.0
info:
  title: Monstres API
  summary: This is the API of the Monstres service
  description: 
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /monstre:
    post:
      tags:
      - developers
      operationId: add_monstre
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monstre'
components:
  schemas:
    Monstre:
      type: object
      required:
        - id
        - name
        - puissance
        - nb_combats
        - nb_victoires
        - master_id
        - prix 
        - num_equipe
      properties:
        id:
          type: int
          example: 1
        name:
          type: string
          example: "Pikachu"
        puissance:
          type: int
          example: 100
        nb_combats:
          type: int 
          example: 5
        nb_victoires:
          type: int 
          example: 4
        master_id:
          type: int 
          example: 2
        prix:
          type: int 
          example: 200
        num_equipe:
          type: int 
          example: 1


