/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **matchmaking**
   * - Table in database
   */
  export namespace matchmaking {
    export type Table = 'matchmaking';
    export interface Selectable {
      /**
      * **matchmaking.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matchmaking_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matchmaking.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1: number;
      /**
      * **matchmaking.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at: Date | null;
      /**
      * **matchmaking.open**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      open: boolean | null;
    }
    export interface JSONSelectable {
      /**
      * **matchmaking.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matchmaking_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matchmaking.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1: number;
      /**
      * **matchmaking.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at: db.TimestampString | null;
      /**
      * **matchmaking.open**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      open: boolean | null;
    }
    export interface Whereable {
      /**
      * **matchmaking.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matchmaking_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matchmaking.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matchmaking.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matchmaking.open**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      open?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **matchmaking.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matchmaking_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **matchmaking.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **matchmaking.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matchmaking.open**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      open?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **matchmaking.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matchmaking_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **matchmaking.p1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      p1?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **matchmaking.created_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matchmaking.open**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      open?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'matchmaking_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = matchmaking.Table;
    export type Selectable = matchmaking.Selectable;
    export type JSONSelectable = matchmaking.JSONSelectable;
    export type Whereable = matchmaking.Whereable;
    export type Insertable = matchmaking.Insertable;
    export type Updatable = matchmaking.Updatable;
    export type UniqueIndex = matchmaking.UniqueIndex;
    export type Column = matchmaking.Column;
  
    export type AllBaseTables = [matchmaking.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [matchmaking.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "matchmaking": matchmaking.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "matchmaking": matchmaking.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "matchmaking": matchmaking.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "matchmaking": matchmaking.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "matchmaking": matchmaking.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "matchmaking": matchmaking.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "matchmaking": matchmaking.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "matchmaking": matchmaking.SQL;
  }[T];

}
