/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **messages**
   * - Table in database
   */
  export namespace messages {
    export type Table = 'messages';
    export interface Selectable {
      /**
      * **messages.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number;
      /**
      * **messages.sent_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      sent_at: Date | null;
      /**
      * **messages.from_id**
      * - `int4` in database
      * - Nullable, no default
      */
      from_id: number | null;
      /**
      * **messages.to_id**
      * - `int4` in database
      * - Nullable, no default
      */
      to_id: number | null;
      /**
      * **messages.content**
      * - `text` in database
      * - Nullable, no default
      */
      content: string | null;
    }
    export interface JSONSelectable {
      /**
      * **messages.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number;
      /**
      * **messages.sent_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      sent_at: db.TimestampString | null;
      /**
      * **messages.from_id**
      * - `int4` in database
      * - Nullable, no default
      */
      from_id: number | null;
      /**
      * **messages.to_id**
      * - `int4` in database
      * - Nullable, no default
      */
      to_id: number | null;
      /**
      * **messages.content**
      * - `text` in database
      * - Nullable, no default
      */
      content: string | null;
    }
    export interface Whereable {
      /**
      * **messages.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **messages.sent_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      sent_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **messages.from_id**
      * - `int4` in database
      * - Nullable, no default
      */
      from_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **messages.to_id**
      * - `int4` in database
      * - Nullable, no default
      */
      to_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **messages.content**
      * - `text` in database
      * - Nullable, no default
      */
      content?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **messages.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **messages.sent_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      sent_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **messages.from_id**
      * - `int4` in database
      * - Nullable, no default
      */
      from_id?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **messages.to_id**
      * - `int4` in database
      * - Nullable, no default
      */
      to_id?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **messages.content**
      * - `text` in database
      * - Nullable, no default
      */
      content?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **messages.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **messages.sent_at**
      * - `timestamp` in database
      * - Nullable, no default
      */
      sent_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **messages.from_id**
      * - `int4` in database
      * - Nullable, no default
      */
      from_id?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **messages.to_id**
      * - `int4` in database
      * - Nullable, no default
      */
      to_id?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **messages.content**
      * - `text` in database
      * - Nullable, no default
      */
      content?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'messages_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = messages.Table;
    export type Selectable = messages.Selectable;
    export type JSONSelectable = messages.JSONSelectable;
    export type Whereable = messages.Whereable;
    export type Insertable = messages.Insertable;
    export type Updatable = messages.Updatable;
    export type UniqueIndex = messages.UniqueIndex;
    export type Column = messages.Column;
  
    export type AllBaseTables = [messages.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [messages.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "messages": messages.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "messages": messages.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "messages": messages.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "messages": messages.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "messages": messages.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "messages": messages.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "messages": messages.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "messages": messages.SQL;
  }[T];

}
